[workspace]
release_always = false
changelog_update = true
git_tag_enable = true
git_release_enable = true
git_tag_name = "{{ package }}-v{{ version }}"
git_release_name = "{{ package }} v{{ version }}"
git_release_body = "{{ changelog }}"

[[package]]
name = "league-mod"
publish = false
changelog_update = true

[[package]]
name = "ltk_fantome"
publish = true
changelog_update = true

[[package]]
name = "ltk_modpkg"
publish = true
changelog_update = true

[[package]]
name = "ltk_mod_project"
publish = true
changelog_update = true

[[package]]
name = "ltk_pki"
publish = true
changelog_update = true

[[package]]
name = "ltk-manager"
publish = false
changelog_update = true

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
